package com.sbs.internetbanking.enums;

/*public enum RequestType {
    PENDING_APPROVAL,
    ACCOUNT_APPROVAL,
    DEBIT_REQUEST,
    CREDIT_REQUEST,
    TRANSFER_REQUEST,
    VIEW_TRANSACTIONS_REQUEST,
    MODIFY_TRANSACTIONS_REQUEST,
    VIEW_USERINFO_REQUEST,
    UPDATE_USERINFO_REQUEST,
    APPROVED,
    DECLINED;
}*/
public enum RequestType {
    CREATE_ACCOUNT,
    MODIFY_ACCOUNT,
    DELETE_ACCOUNT,
    VIEW_ACCOUNT,
    VIEW_TRANSACTION,
    DELETE_TRANSACTION,
    MODIFY_TRANSACTION,
    CREDIT_REQUEST,
}
